name: Win64

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  raku:
    strategy:
      matrix:
        os:
          - windows-latest
        raku-version:
          - 'latest'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - name: Install Dependencies
        run: |
          zef install --/test --deps-only .
          zef install --/test App::Prove6
      - name: Run Tests
        run: |
          raku -I. t/01-creation.rakutest
          raku -I. t/02-basic-use.rakutest
          raku -I. t/03-representation.rakutest
          raku -I. t/04-remove-by-threshold.rakutest
          raku -I. t/05-remove-by-pareto.rakutest
        run: prove6 -l t
